version: "3.7"
services:
  app:
    container_name: unitime-api
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - caddy
      - db
    labels:
      caddy: unitime-api.aomdev.com
      caddy.reverse_proxy: "{{ upstreams 3000 }}"
networks:
  db:
    external: true
  caddy:
    external: true